#!/usr/bin/env node

/**
 * Setup Script
 * Interactive setup wizard for token refresher agent
 */

import fs from 'fs/promises';
import path from 'path';
import { fileURLToPath } from 'url';
import readline from 'readline';
import chalk from 'chalk';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout
});

function question(query) {
  return new Promise(resolve => rl.question(query, resolve));
}

async function setup() {
  console.log(chalk.bold.cyan('\n🚀 Token Refresher Agent - Setup Wizard\n'));
  console.log(chalk.gray('This wizard will help you configure the token refresher agent.\n'));
  
  // Check if .env already exists
  const envPath = path.join(__dirname, '.env');
  let existingEnv = '';
  try {
    existingEnv = await fs.readFile(envPath, 'utf-8');
    console.log(chalk.yellow('⚠ Found existing .env file. You can update it or press Enter to keep existing values.\n'));
  } catch (error) {
    console.log(chalk.gray('No existing .env file found. Creating a new one.\n'));
  }
  
  // Parse existing values
  const existingValues = {};
  existingEnv.split('\n').forEach(line => {
    const match = line.match(/^([^=]+)=(.*)$/);
    if (match) {
      existingValues[match[1].trim()] = match[2].trim();
    }
  });
  
  // Collect configuration
  console.log(chalk.bold('1. Authentication Credentials'));
  console.log(chalk.gray('   These will be used to authenticate with your API\n'));
  
  const username = await question(
    chalk.cyan(`   Username ${existingValues.AUTH_USERNAME ? `(current: ${existingValues.AUTH_USERNAME})` : ''}: `)
  ) || existingValues.AUTH_USERNAME || '';
  
  const password = await question(
    chalk.cyan(`   Password ${existingValues.AUTH_PASSWORD ? '(current: ********)' : ''}: `)
  ) || existingValues.AUTH_PASSWORD || '';
  
  console.log(chalk.bold('\n2. API Configuration'));
  console.log(chalk.gray('   The authentication endpoint URL\n'));
  console.log(chalk.gray('   Examples:'));
  console.log(chalk.gray('   - https://auth.talarianweb.com/oauth2/token'));
  console.log(chalk.gray('   - http://ociqaintx.talarianweb.com:8080/api/auth\n'));
  
  const endpoint = await question(
    chalk.cyan(`   API Endpoint ${existingValues.AUTH_API_ENDPOINT ? `(current: ${existingValues.AUTH_API_ENDPOINT})` : ''}: `)
  ) || existingValues.AUTH_API_ENDPOINT || '';
  
  console.log(chalk.bold('\n3. Refresh Interval'));
  console.log(chalk.gray('   How often should tokens be refreshed (cron format)\n'));
  console.log(chalk.gray('   Common intervals:'));
  console.log(chalk.gray('   - */15 * * * * = Every 15 minutes'));
  console.log(chalk.gray('   - */30 * * * * = Every 30 minutes (recommended)'));
  console.log(chalk.gray('   - 0 * * * * = Every hour'));
  console.log(chalk.gray('   - 0 */2 * * * = Every 2 hours\n'));
  
  const interval = await question(
    chalk.cyan(`   Refresh Interval ${existingValues.REFRESH_INTERVAL ? `(current: ${existingValues.REFRESH_INTERVAL})` : '(default: */30 * * * *)'}: `)
  ) || existingValues.REFRESH_INTERVAL || '*/30 * * * *';
  
  rl.close();
  
  // Create .env content
  const envContent = `# Authentication Configuration
# Generated by setup wizard on ${new Date().toLocaleString()}

AUTH_USERNAME=${username}
AUTH_PASSWORD=${password}

# API Endpoint for authentication
AUTH_API_ENDPOINT=${endpoint}

# Refresh interval (cron expression)
REFRESH_INTERVAL=${interval}

# Optional: Path to token service file (relative to this directory)
# TOKEN_SERVICE_PATH=../../libs/core/src/lib/services/token.service.ts
`;
  
  // Save .env file
  try {
    await fs.writeFile(envPath, envContent);
    console.log(chalk.green('\n✓ Configuration saved to .env file'));
  } catch (error) {
    console.error(chalk.red('\n✗ Failed to save configuration:'), error.message);
    console.log(chalk.yellow('\nManually create .env file with:'));
    console.log(envContent);
    process.exit(1);
  }
  
  // Verify configuration
  console.log(chalk.cyan('\n📋 Your Configuration:'));
  console.log(chalk.gray('  Username:'), username || chalk.red('NOT SET'));
  console.log(chalk.gray('  Password:'), password ? '********' : chalk.red('NOT SET'));
  console.log(chalk.gray('  Endpoint:'), endpoint || chalk.red('NOT SET'));
  console.log(chalk.gray('  Interval:'), interval);
  
  // Validation
  const missingFields = [];
  if (!username) missingFields.push('username');
  if (!password) missingFields.push('password');
  if (!endpoint) missingFields.push('endpoint');
  
  if (missingFields.length > 0) {
    console.log(chalk.red('\n⚠ Warning: Missing required fields:'), missingFields.join(', '));
    console.log(chalk.yellow('Edit .env file to add missing values before running the agent.'));
  } else {
    console.log(chalk.green('\n✓ Configuration complete!'));
    console.log(chalk.cyan('\n📝 Next Steps:'));
    console.log(chalk.gray('  1. Test your configuration:'), chalk.cyan('npm run test'));
    console.log(chalk.gray('  2. Do a manual refresh:'), chalk.cyan('npm run refresh'));
    console.log(chalk.gray('  3. Start auto-refresh:'), chalk.cyan('npm run auto'));
    console.log(chalk.gray('  4. View cached token:'), chalk.cyan('npm run view\n'));
  }
  
  console.log(chalk.gray('\n💡 Tip: You can re-run this setup anytime with:'), chalk.cyan('npm run setup\n'));
}

setup().catch(error => {
  console.error(chalk.red('Setup failed:'), error);
  process.exit(1);
});
